USE [master]
GO

/****** Object:  Database [PharmaGoDb]    Script Date: 12/11/2023 22:15:45 ******/
CREATE DATABASE [PharmaGoDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PharmaGoDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PharmaGoDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PharmaGoDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PharmaGoDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PharmaGoDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PharmaGoDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PharmaGoDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PharmaGoDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PharmaGoDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PharmaGoDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [PharmaGoDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PharmaGoDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PharmaGoDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PharmaGoDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PharmaGoDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PharmaGoDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PharmaGoDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PharmaGoDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PharmaGoDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PharmaGoDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PharmaGoDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PharmaGoDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PharmaGoDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PharmaGoDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PharmaGoDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PharmaGoDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PharmaGoDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PharmaGoDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PharmaGoDb] SET  MULTI_USER 
GO

ALTER DATABASE [PharmaGoDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PharmaGoDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PharmaGoDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PharmaGoDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PharmaGoDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PharmaGoDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PharmaGoDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PharmaGoDb] SET  READ_WRITE 
GO

